LemireCoding/BuiltDifferentMobileApp

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/INetworkService.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/NetworkService.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/WorkoutManageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/WorkoutViewModel.cs

JIRA: [BUILT-56](https://champlainsaintlambert.atlassian.net/browse/BUILT-56?atlOrigin=eyJpIjoiZTgxNGJlODFiYmQzNDMwN2EzMWVhNDIzMjc3OTY2NmQiLCJwIjoiaiJ9)
Just some mini refactoring in APIConstants and implemented all the HTTP methods in NetworkService.
Do note that the methods now return an object instead of an HTTP status.
- Refactored APIConstants and changed method names
- Added missing HTTP methods in INetworkService
- Implemented NetworkService methods
- Modified calls to renamed methods & checking if status was OK in some View Models

conf(BUILT-56): Network Service methods & APIConstants refactoring

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/LoginPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/LoginPage.xaml.cs

JIRA: [BUILT-xxx](https://champlainsaintlambert.atlassian.net/browse/BUILT-44?atlOrigin=eyJpIjoiMjljNmVjNjY0NzJmNGY1ODhjMTQ1MmY1ZjgyOGMwOGEiLCJwIjoiaiJ9)
This story allows a logged in user to log out, which then clears their JWT token & saved user info in the AccountService.
- Added flyout logout button
- Added OnAppearing for LoginPage to clear credentials
log out button go brrrr

feat(BUILT-44): Added logout

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/CreateAccountTests.cs
BuiltDifferent.UITest/SignupTests.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/AccountCreatedResponse.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/INetworkService.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/NetworkService.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Login/RegisterPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Login/LoginPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Login/RegisterPage.xaml

JIRA: [BUILT-57](https://champlainsaintlambert.atlassian.net/browse/BUILT-57?atlOrigin=eyJpIjoiNWEzZGU5YTBlZDUzNDNiYTk1MzljNTU5OTk5NmUzZGUiLCJwIjoiaiJ9)
This story allows the user to be able to create an account through the app as either a coach or a client.
- Added appropriate inputs to register page
- Register function in NetworkService
- Added error handling
- Added password requirements (Must contain 8 characters, at least one uppercase, symbol and a number)
- Added email requirements (Must be a valid email)
- Added tests for registering & testing errors

feat(BUILT-57): Account Registration

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/ProfileTests.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/Client.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/ClientProfileDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Profile/MyProfilePageClientViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientDashboardPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Profile/MyProfilePageClient.xaml

JIRA: [BUILT-11](https://champlainsaintlambert.atlassian.net/browse/BUILT-11?atlOrigin=eyJpIjoiNTUwYjNhNzgzY2ZjNDk1Mzk0OTA5YmIxZjg2ZjdkNjgiLCJwIjoiaiJ9)
This story. is the front end of the update and get profile for the logged in user.
Client Model now has startweight, currentweight, profilePicture fields.

Feat/BUILT-11 Client Profile

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Login/RegisterPageViewModel.cs

JIRA: [BUILT-76](https://champlainsaintlambert.atlassian.net/browse/BUILT-76?atlOrigin=eyJpIjoiYTdlNDJjMDM3ZGVkNGY4MDg1OGQxYzdmNzBiMjc0MGMiLCJwIjoiaiJ9)

bug(BUILT-76): Fixed name sending twice

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/ForgotPassword/ForgotPasswordPageViewModel.cs

*Note* Sorry about the branch naming will ensure this is not produced again.
JIRA: [BUILT-74](https://champlainsaintlambert.atlassian.net/browse/BUILT-74?atlOrigin=eyJpIjoiNTQ5ODk1NzNmMjIwNDk5ZmJkZTQ0MGUzMzViNzgxMzEiLCJwIjoiaiJ9)
This bug fix is a minor fix to ensure the error message is removed when the success message appears.
n/a

bug/BUILT-74_Forgotten Password Error message fix

---

BuiltDifferent.UITest/AdminInteractWithCoachAccountsTests.cs
BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/BuiltDifferentMobileApp.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/NetworkService.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Admin/AdminApprovedCoachProfilePageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Admin/AdminApprovedCoachesPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Admin/AdminCoachApprovalProfilePageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminApprovedCoachProfilePage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminApprovedCoachProfilePage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminApprovedCoachesPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminApprovedCoachesPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminCoachApprovalProfilePage.xaml

JIRA: [BUILT-24](https://champlainsaintlambert.atlassian.net/browse/BUILT-24?atlOrigin=eyJpIjoiY2EyODUwZDNlZDk4NDUxMzhiYzg5MDU4ZDU1MzA4NDciLCJwIjoiaiJ9)
This story allows an admin to view verified coaches and their profiles.
Views are nearly identical to pending coaches list & profile page.
- Added verified coaches page
- Added verified coaches page profile
- Added page to admins flyout
- Added tests

feat(BUILT-24): Admin Coach Monitoring

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/MarkAsDoneMeal.cs
BuiltDifferent.UITest/MarkAsDoneWorkout.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/BuiltDifferentMobileApp.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToColorButtonMealEatenConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToColorButtonWorkoutDoneConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToTextButtonMealEatenConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToTextButtonWorkoutDoneConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientWorkoutViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/AddMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/AddWorkoutViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientCoachSelectionPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientDashboardPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientDashboardPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientMealPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientMealPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientWorkoutPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientWorkoutPage.xaml.cs

JIRA: (https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-10)
This story englobes BUILT-18 BUILT-16 BUILT-19 BUILT-17 and it consists into creating the whole dashboard for the client where he can see his meals and workouts scheduled on specific days.
Added new pages and viewmodels for the dashboard

 feat(BUILT-10): Client Dashboard

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.Designer.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.fr.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/NewCoachPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/NewCoachPage.xaml

JIRA: [BUILT-64](https://champlainsaintlambert.atlassian.net/browse/BUILT-64?atlOrigin=eyJpIjoiMTI1OTQzNDQ0MTY1NDMzYWFiMWJhNjk5NjRkOTNjYTIiLCJwIjoiaiJ9)
This branch adds translations for French on the New Coach Application page.

conf(BUILT-64): New Coach Page Translation

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/Request.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/RequestDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientCoachSelectionViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientCoachSelectionPage.xaml

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-69
Front-end side of things to allow the user to request a coach
added a request dto and a command to the selectionViewModel

feat/BUILT-69 Client Request A Coach

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.fr.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/CoachMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Profile/MyProfilePageClientViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachMenuPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachWorkoutPage.xaml

JIRA: [BUILT-79](https://champlainsaintlambert.atlassian.net/browse/BUILT-79?atlOrigin=eyJpIjoiZTdhZWZiOTNmNmY5NDRhMGJmODBkOWE4NTlkNDViYmIiLCJwIjoiaiJ9)
Fixing a bug found when a coach attempt to retrieve a clients board and the name of the page is changed to english, now fixed.

bug/BUILT-79 - coachmenu page title changed.

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientDashboardPage.xaml

Removed Random character that was generated in last pr

Bug/Built-85 Client Login Check If Has Coach

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp.Android/Resources/Resource.designer.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/NewCoachPageViewModel.cs

JIRA: [BUILT-97](https://champlainsaintlambert.atlassian.net/browse/BUILT-97?atlOrigin=eyJpIjoiYzdlYTFmNmUzY2RiNGMzZWJjMDA3MzVmM2Q5NDkxMmYiLCJwIjoiaiJ9)
This story fixes a bug with French data being sent instead of English.
- Added conversion to English for gender

bug(BUILT-97): Fixed French Data Sending

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/ClientWithProgress.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/CoachDashboardPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachDashboardPage.xaml

Filter fixed
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21/backlog?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-100
This story is to display the real % of daily completed tasks for each clients in the coach list
changed the ViewModel of the CoachDashboard page

feat(BUILT-100): Show Client's % Tasks Completed To Coach 

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/ClientPlanTests.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToExpandOrCompletedIconConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToSelectedWeekdayColorConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientWorkoutViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientDashboardPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientMealPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientWorkoutPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachMenuPage.xaml.cs

JIRA: [BUILT-95](https://champlainsaintlambert.atlassian.net/browse/BUILT-95?atlOrigin=eyJpIjoiMGQ2NWI1ZWUyNjExNDQzYmE3N2Q0ODRiYTUyODIyMTMiLCJwIjoiaiJ9)
This story reworks the old calendar into a custom week selector.
- Reworked UI
- Coded custom date selector

feat(BUILT-95): Update Date Picker

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/ClientRequestCenterTest.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/BuiltDifferentMobileApp.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/Request.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.Designer.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.fr.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientCoachSelectionViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientRequestsCenterViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientRequestsCenterPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientRequestsCenterPage.xaml.cs

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21/backlog?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-101
New ClientRequestsCenterPage with its viewmodel
Added Unit and End-to-End Tests

feat(BUILT-101): Client Can view his previous / Pending Requests

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/ProgressBarWorkoutTest.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientWorkoutViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientWorkoutPage.xaml

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21/backlog?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-81
This story consisted of coding the logic for the progression bar for workouts

Feat/BUILT-81 Client Can See Their Daily Workout Completion

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/MealProgressionBar.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientMealPage.xaml

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21/backlog?assignee=6005c6881ffcc00076745e8b&selectedIssue=BUILT-82
This story consisted of making the logic for the progression bar of the meals

Feat/BUILT-82 Clients Can See Their Daily Meal Completion

---

BuiltDifferent.UITest/BuiltDifferent.UITest.csproj
BuiltDifferent.UITest/ClientPaymentTests.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp.Android/Resources/Resource.designer.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/BuiltDifferentMobileApp.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/Coach.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/CoachPaymentDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/CoachProfileDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/NewCoachPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Payment/PaymentViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Profile/MyProfilePageCoachViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/NewCoachPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Payment/PaymentPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Payment/PaymentPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Profile/MyProfilePageCoach.xaml

JIRA: [BUILT-20](https://champlainsaintlambert.atlassian.net/browse/BUILT-20?atlOrigin=eyJpIjoiZDIxMDBiNzYyNzlhNDk3YWFkZTAyOTc5MDljNGE3Y2UiLCJwIjoiaiJ9)
This story aims to allow clients to pay their coach using a PayPal link, this payment page is only accessible to client who have been accepted by a coach. This page includes the coach name , the client name and the price associated, the button will then redirect them to the coach PayPal link within their default browser.
new Payment page.

Feat/BUILT-20 payment payPal redirect

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/BuiltDifferentMobileApp.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/Client.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/ClientProfileDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/ClientReportInfo.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/CoachReport.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Coach/CoachSummaryReportViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Profile/MyProfilePageClientViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Profile/MyProfilePageCoachViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachSummaryReportPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachSummaryReportPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Profile/MyProfilePageClient.xaml

JIRA: [BUILT-96](https://champlainsaintlambert.atlassian.net/browse/BUILT-96?atlOrigin=eyJpIjoiMTA3NjY3NWQ5MWYyNDI0ODlkMGM5NzI0NjU2ZjI1NDQiLCJwIjoiaiJ9)
Thjis story aims to allow coaches to view their weekly report on their clients and how many clients they are currently coaching.
The client informationc ontained is bmi, caliries consumed and workouts done.
Client Profile, to include height , summary report  page for coaches.

feat/BUILT-96 Coach Report

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp.Android/BuiltDifferentMobileApp.Android.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp.iOS/BuiltDifferentMobileApp.iOS.csproj
BuiltDifferentMobileApp/BuiltDifferentMobileApp/AppShell.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/CertificationDetailsDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Models/UserDateRoleDTO.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/BoolToGreyedOutConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/DateToVisibleBooleanConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/Converters/IntToGreyedOutOnPositiveConverter.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Services/NetworkServices/APIConstants.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Admin/AdminMenuPageViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientMealViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientWorkoutViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminMenuPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Admin/AdminMenuPage.xaml.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientMealPage.xaml
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientWorkoutPage.xaml

JIRA: [BUILT-93](https://champlainsaintlambert.atlassian.net/browse/BUILT-93?atlOrigin=eyJpIjoiZjllNmY5ZmE3ZDVlNDQ3MWEzNTBhZTBjNWYxNDY2MTUiLCJwIjoiaiJ9)
This story adds a dynamic weekly reports page.
- Miscellaneous UI improvements
- Added reports page to existing admin menu page
- Changed flyout color

feat(BUILT-93): Admin Summary Report

---

BuiltDifferent.UITest/ClientPlanTests.cs
BuiltDifferent.UITest/ClientProfileTests.cs
BuiltDifferent.UITest/CoachProfileTests.cs
BuiltDifferent.UITest/CoachSummaryReportTests.cs
BuiltDifferent.UITest/ForgotPasswordTests.cs
BuiltDifferent.UITest/MarkAsDoneMeal.cs
BuiltDifferent.UITest/MarkAsDoneWorkout.cs
BuiltDifferent.UITest/MealRecipeTest.cs
BuiltDifferent.UITest/MealTests.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Coach/CoachSummaryReportPage.xaml

JIRA: [BUILT-102](https://champlainsaintlambert.atlassian.net/browse/BUILT-102?atlOrigin=eyJpIjoiOTczYzJlOGZjMTlkNDAyMTk4ZDE5YWZjYTk3MWE2NDkiLCJwIjoiaiJ9)
Part 2
This task is to reset all of the broken tests and ensure a sequence producing no errors, FIXED
-tests, automationId
**NOTE: 3 tests will fail (certification and profilePicture upload client  and profilePicture upload coach)
These require human interaction, ui test does not support file or mediapickers

BUILT-102 - Test Fixing

---

BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.Designer.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.fr.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Ressource/AppResource.resx
BuiltDifferentMobileApp/BuiltDifferentMobileApp/ViewModels/Client/ClientCoachSelectionViewModel.cs
BuiltDifferentMobileApp/BuiltDifferentMobileApp/Views/Client/ClientRequestsCenterPage.xaml

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/BUILT/boards/21/backlog?selectedIssue=BUILT-105
Removed redirection to request center

Bug/BUILT-105 Request Redirection to request center bug
